### ISSUE TITLE
Failed to activate the termination package

### ISSUE THREAD

**Issue by ddavidebor** [Fred-Barclay/Termination#13]
# dump:

**Atom Version**: 1.12.4
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [termination](https://github.com/Fred-Barclay/Termination) package, v0.3.3

### Stack Trace

Failed to activate the termination package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'pio-terminal-status-icon'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'pio-terminal-status-icon'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/davidebortolami/.atom/packages/termination/lib/status-icon.coffee:100:27)
    at Object.<anonymous> (/Users/davidebortolami/.atom/packages/termination/lib/status-icon.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/davidebortolami/.atom/packages/termination/lib/status-bar.coffee:5:14)
    at Object.<anonymous> (/Users/davidebortolami/.atom/packages/termination/lib/status-bar.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.consumeStatusBar (/Users/davidebortolami/.atom/packages/termination/lib/termination.coffee:17:27)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:364:75)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:187:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:350:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:171:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:358:27)
    at HTMLButtonElement.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:29.6.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:47.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:35.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:30.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:28.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "gist-it",
      "markdown-preview",
      "language-gfm",
      "makro",
      "project-runner",
      "make-runner-panel",
      "linter-spell",
      "linter-write-good",
      "atom-terminal",
      "terminal-plus",
      "rst-preview-pandoc",
      "platformio-ide-terminal"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "genesis-ui",
      "genesis-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aesthetic-ui, v2.0.0 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-spotify2, v2.1.2 (active)
atom-terminal, v0.8.0 (inactive)
auto-detect-indentation, v1.3.0 (active)
battery-status, v0.11.0 (active)
compare-files, v0.8.0 (active)
file-icons, v1.7.25 (active)
genesis-syntax, v1.0.7 (active)
genesis-ui, v0.5.0 (active)
git-plus, v5.25.3 (active)
git-time-machine, v1.5.4 (inactive)
hex, v0.6.2 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
intel-hex, v0.1.0 (active)
intentions, v1.1.2 (active)
jekyll, v1.4.3 (inactive)
jekyll-snippets, v0.3.2 (inactive)
language-ansible, v0.1.11 (active)
language-arduino, v0.4.2 (active)
language-docker, v1.1.7 (active)
language-pfm, v0.82.0 (active)
language-tex, v0.4.0 (active)
linter, v1.11.18 (active)
linter-alex, v3.2.0 (active)
linter-ansible-linting, v1.2.1 (active)
linter-docker, v0.1.2 (active)
linter-js-yaml, v1.2.5 (active)
linter-jsonlint, v1.3.0 (active)
linter-just-say-no, v0.7.0 (active)
linter-proselint, v3.2.0 (active)
linter-shellcheck, v1.4.1 (active)
linter-spell, vundefined (inactive)
linter-spell-html, v0.6.1 (inactive)
linter-spell-javascript, v0.7.1 (inactive)
linter-spell-ruby, v0.3.1 (inactive)
linter-write-good, v0.8.0 (inactive)
make-runner, v1.1.14 (inactive)
make-runner-panel, v1.4.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
markdown-themeable-pdf, v1.2.0 (active)
markdown-writer, v2.6.2 (inactive)
minimap, v4.25.6 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minimap-pigments, v0.2.1 (active)
open-recent, v5.0.0 (active)
path-copy, v0.14.0 (active)
pdf-view, v0.53.0 (active)
php-twig, v4.0.0 (active)
pigments, v0.37.0 (active)
platformio-ide-terminal, v2.2.2 (inactive)
project-runner, v0.5.1 (inactive)
rst-preview-pandoc, v0.1.12 (inactive)
script, v3.11.1 (inactive)
sync-settings, v0.7.2 (active)
terminal-plus, v0.14.5 (inactive)
termination, v0.3.3 (inactive)
todo-show, v1.8.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ddavidebor** [comment]
Uninstalling other terminal packages does not help

**Comment by Fred-Barclay** [comment]
It's a cosmetic bug. I've gotten the same message when I uninstall/deactivate platformio-ide-terminal and install/activate termination without restarting Atom. These two packages share a code snippet that's causing the trouble. `termination` works just fine, though, if you restart Atom and doesn't produce any more warnings.

Try this:
Activate termination (if you've deactivated it)
See if it gives any warnings and copy them
Restart Atom
Does termination work?

**Comment by ddavidebor** [comment]
Yes that was the problem.
(but for now it does not work, empty terminal.. will get back to you later)

**Comment by Fred-Barclay** [comment]
No worries - thanks for the report! I'm sending in a fix in a few minutes.
