### ISSUE TITLE
Blank screen upon open Termination

### ISSUE THREAD

**Issue by Stefanbracke** [Fred-Barclay/Termination#22]
I see this in console:

_'termination.core.shell' could not set the default. Attempted default: undefined; Schema: {"title":"Shell Override","description":"Override the default shell instance to launch.","type":"string"}_

Termination worked as normal but after restarting my macos 10.12 I get this error in new projects.
Where do i set this shell?? 

The result of the above is an error:

_Path must be a string. Received null TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1357:5)
    at Object.module.exports (/Users/stef/.atom/packages/termination/lib/process.coffee:32:24)
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:84:10)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)_

**Comment by Fred-Barclay** [comment]
Hi @Stefanbracke 
Can I grab this info from you?
```
    Version of Atom
    Version of Termination
    Operating System
    Any debug information
    Steps to reproduce the problem

Screenshots/GIFs are always welcome and worth a thousand words! (How?)
```

**Comment by Stefanbracke** [comment]
Atom: 1.13.1  x64
Termination: 0.3.6
OS: macos 10.12

**Comment by Fred-Barclay** [comment]
Screenshots would definitely be helpful. I can't replicate it on my end... might be another one of those macOS-specific bugs.... grrrr.

(No mac here but I will try to fix it. :smile:)

**Comment by Fred-Barclay** [comment]
@Stefanbracke We've made a few changes (two of which are significant) to Termination recently. Can you check and see if this is still active with the latest release?

Cheers!
