### ISSUE TITLE
Uncaught TypeError: Cannot read property 'maximize' of null

### ISSUE THREAD

**Issue by mannyhagman** [Fred-Barclay/Termination#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [Termination](https://github.com/Fred-Barclay/Termination) package, v0.1.4
### Stack Trace

Uncaught TypeError: Cannot read property 'maximize' of null

```
At /Users/mannyhagman/.atom/packages/Termination/lib/status-bar.coffee:49

TypeError: Cannot read property 'maximize' of null
    at atom-workspace.subscriptions.add.atom.commands.add.termination:fullscreen (/Users/mannyhagman/.atom/packages/Termination/lib/status-bar.coffee:49:51)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1127:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:341:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```
### Commands

```
     -2:02.4.0 platformio-ide-terminal:new (ul.list-inline.tab-bar.inset-panel)
     -1:46 termination:new (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:28.7.0 termination:close-all (atom-text-editor.editor.is-focused)
     -0:24.2.0 termination:new (atom-text-editor.editor.is-focused)
     -0:11.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.7.0 platformio-ide-terminal:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 termination:fullscreen (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-ternjs",
      "highlight-selected",
      "activate-power-mode",
      "welcome"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "useCustomTitleBar": true
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v1.1.0 (inactive)
atom-beautify, v0.29.13 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-ternjs, v0.15.0 (inactive)
highlight-selected, v0.11.2 (inactive)
markdown-preview-plus, v2.4.0 (active)
native-ui, v0.19.1 (inactive)
nucleus-dark-ui, v0.10.12 (inactive)
selection-highlight, v0.1.5 (active)
Termination, v0.1.4 (active)
unity-ui, v2.1.6 (inactive)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Fred-Barclay** [comment]
Thanks for the bug! (Should I really be *thanking* you for a bug? :stuck_out_tongue_winking_eye: ) I'm afraid I'm horrid with coffescript so it might take a while to get this straightened out.

**Comment by mannyhagman** [comment]
No worries! I basically just clicked on the error window in atom and it automatically created the issue. Good luck with the coffee script!

**Comment by Fred-Barclay** [comment]
@mannyhagman: I've got a potential fix in on a "dummy" Atom package. Could you install faketerm2 in Atom and let me know if it works?

**Comment by mannyhagman** [comment]
Yes for sure. I'll update you soon.

**Comment by mannyhagman** [comment]
@Fred-Barclay 
Wow. fakeTerm2 is awesome. So far the best terminal package I have used on Atom. 
![screen shot 2016-10-30 at 12 37 38 am](https://cloud.githubusercontent.com/assets/7909800/19834846/5f507cfe-9e3f-11e6-9fe9-7cdb205b31d9.png)

**Comment by mannyhagman** [comment]
![image](https://cloud.githubusercontent.com/assets/7909800/19834974/db52f89a-9e44-11e6-8792-597969a408c4.png)

**Comment by Fred-Barclay** [comment]
Great! I'll be getting a fix in as soon as possible, then. You may see some weird stuff going on with termination or faketerm2 - just ignore it and **don't** update! :smile: I'll comment back here once the situation has stabilised.

**Comment by Fred-Barclay** [comment]
Alright, hopefully termination is fixed. :tada: :  You'll need to completely uninstall it (if you haven't already) since I've reset the version numbers.

**Comment by mannyhagman** [comment]
Thanks Fred, I'll be able to do that a bit later today and let you know what he results are.

**Comment by Fred-Barclay** [comment]
Sounds good. Let me know when you find out (plus any suggestions, etc.) :smile:
