### ISSUE TITLE
Error while apm install

### ISSUE THREAD

**Issue by Timemashine** [Fred-Barclay/Termination#34]
Found the package and wanted to install it with `apm install`

```
$  apm install termination                                                                           .
Installing termination to /Users/andre/.atom/packages ✗

module.js:327
    throw err;
    ^

Error: Cannot find module 'concat-map'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/brace-expansion/index.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

I closed Atom and tried again:

```
$  apm install termination                                                                           .
Installing termination to /Users/andre/.atom/packages ✓
```

**Comment by Fred-Barclay** [comment]
Hi @Timemashine and thanks for trying Termination! :smile: 
So you can install Termination when Atom is closed but not when it is open?
That sounds (possibly) like the issue may be on Atom's end. 

Can I get this info from you?
[CONTRIBUTING.md#filing-an-issue](https://github.com/Fred-Barclay/Termination/blob/master/CONTRIBUTING.md#filing-an-issue)

**Comment by Timemashine** [comment]
I forget to say, after the 2. try it was installed successful.

Atom version 1.14.4
apm version 1.15.3

```
Built-in Atom Packages (89)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.4.0
├── base16-tomorrow-light-theme@1.4.0
├── one-dark-ui@1.9.1
├── one-light-ui@1.9.1
├── one-dark-syntax@1.6.0
├── one-light-syntax@1.6.0
├── solarized-dark-syntax@1.1.1
├── solarized-light-syntax@1.1.1
├── about@1.7.2
├── archive-view@0.62.2
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.14.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.34.2
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.0
├── background-tips@0.26.1
├── bookmarks@0.43.4
├── bracket-matcher@0.85.2
├── command-palette@0.39.2
├── deprecation-cop@0.56.2
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.41.0
├── find-and-replace@0.206.3
├── fuzzy-finder@1.4.1
├── git-diff@1.2.0
├── go-to-line@0.31.2
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.1
├── link@0.31.2
├── markdown-preview@0.159.6
├── metrics@1.1.3
├── notifications@0.66.1
├── open-on-github@1.2.1
├── package-generator@1.0.2
├── settings-view@0.246.0
├── snippets@1.0.5
├── spell-check@0.70.2
├── status-bar@1.7.0
├── styleguide@0.48.0
├── symbols-view@0.114.0
├── tabs@0.104.1
├── timecop@0.33.2
├── tree-view@0.213.1
├── update-package-dependencies@0.10.0
├── welcome@0.36.0
├── whitespace@0.36.1
├── wrap-guide@0.39.0
├── language-c@0.54.1
├── language-clojure@0.22.1
├── language-coffee-script@0.48.2
├── language-csharp@0.14.2
├── language-css@0.41.0
├── language-gfm@0.88.0
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.1
├── language-hyperlink@0.16.1
├── language-java@0.25.0
├── language-javascript@0.125.1
├── language-json@0.18.3
├── language-less@0.30.0
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.9.0
├── language-python@0.45.1
├── language-ruby@0.70.4
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.1
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.2
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.15
└── language-yaml@0.27.2

Community Packages (62) /Users/andre/.atom/packages
├── advanced-open-file@0.16.5
├── api-docs@0.0.6
├── atom-beautify@0.29.16
├── atom-live-server@2.1.0
├── atom-material-ui@1.3.9
├── browser-plus@0.0.87
├── chrome-color-picker@0.8.0
├── composer@0.5.0
├── cson@2.0.1
├── docblockr@0.9.1
├── emmet@2.4.3
├── expose@0.13.0
├── file-header@1.13.1
├── file-icons@2.0.15
├── file-templates@0.2.0
├── flex-tool-bar@0.11.0
├── git-control@0.8.2
├── git-plus@7.3.2
├── git-projects@1.17.0
├── git-time-machine@1.5.4
├── glowing-cursor@0.1.2
├── highlight-selected@0.12.0
├── hyperclick@0.0.40
├── intentions@1.1.2
├── keybinding-cheatsheet@0.1.1
├── language-apache@1.7.0
├── language-htaccess@0.1.1
├── language-ini@1.17.0
├── language-log@1.8.0
├── language-markdown@0.19.1
├── linter@1.11.21
├── linter-less@2.6.0
├── linter-php@1.3.1
├── markdown-pdf@1.5.0
├── markdown-preview-plus@2.4.8
├── markdown-writer@2.6.4
├── minimap@4.26.7
├── minimap-linter@1.6.0
├── monokai-fresh-syntax@0.0.2
├── native-color-picker@0.2.0
├── no-file-icons@1.0.0
├── nord-atom-ui@0.9.0
├── outline-selection@0.3.1
├── php-integrator-annotations@1.1.1
├── php-integrator-autocomplete-plus@1.2.0
├── php-integrator-base@2.1.5
├── php-integrator-call-tips@1.2.1
├── php-integrator-linter@1.3.0
├── php-integrator-navigation@1.1.1
├── php-integrator-refactoring@1.3.1
├── php-integrator-tooltips@1.1.3
├── project-plus@0.9.0
├── prompt-big-file@0.3.0
├── save-autorun@0.3.3
├── symbols-tree-view@0.13.2
├── termination@0.5.0
├── tochelet-ui@0.0.0
├── tool-bar@1.0.1
├── tool-bar-main@0.0.10
├── tree-view-autoresize@1.5.0
├── tree-view-git-branch@0.1.2
└── tree-view-git-status@1.3.1
```

**Comment by Fred-Barclay** [comment]
Okay, cool. From what I see this looks like an issue on Atom's end, not ours, but I'll keep this in mind.
Thanks!

**Comment by Timemashine** [comment]
Found the Problem!

The installation failed because of an problem in the apm plugin for [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)

**Comment by Fred-Barclay** [comment]
Great work mate! :+1:
