### ISSUE TITLE
1.12 beta5 broken

### ISSUE THREAD

**Issue by steakknife** [Fred-Barclay/Termination#4]
```
/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/task.js:52 Cannot find module '{{~}}/.atom/packages/terminal-plus/lib/fork.coffee' Error: Cannot find module '{{~}}/.atom/packages/terminal-plus/lib/fork.coffee'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/task-bootstrap.js:110:13)
    at Object.<anonymous> (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/task-bootstrap.js:112:4)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at [eval]:2:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
    at bootstrap_node.js:323:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ /Applications/Atom-Beta.app/Contents/Resources/app.asar/src/task.js:52
/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ /Applications/Atom-Beta.app/Contents/Resources/app.asar/src/task.js:52
```

**Comment by Fred-Barclay** [comment]
I was afraid of that. I'll take a look but my javascript probably isn't good enough to fix this so we'll likely wait and see what the platformio devs do and act accordingly. :smile: 

Thanks for the report!

**Comment by steakknife** [comment]
No worries, I hope to we have more terminal options and you seem to have the most modern fork.

**Comment by steakknife** [comment]
You're probably on the right track, it's probably related to outdated pty.js but I could be wrong. It's the same error in other forks.

**Comment by steakknife** [comment]
See also https://github.com/jeremyramin/terminal-plus/pull/364 might help.

**Comment by Fred-Barclay** [comment]
Thanks mate. I'll take a look at it. :smile:

**Comment by Fred-Barclay** [comment]
I've got a potential fix in. Could you install `faketerm2` in Atom Beta (disable/uninstall termination first and restart Atom or you'll get a cosmetic warning) and see if it works? If so I'll work on getting the code merged here. If not... we'll probably have to wait and see what PlatformIO does. 

Cheers!
Fred

**Comment by steakknife** [comment]
faketerm2 works, jeremyramin/terminal-plus works

**Comment by Fred-Barclay** [comment]
Does it really? I can't get faketerm2 to work (I installed Atom Beta to test) - I get a compile error. Can you walk me through what you do, your environment, etc? 

This looks promising: https://github.com/jeremyramin/terminal-plus/issues/362#issuecomment-256290818

**Comment by steakknife** [comment]
```
(close atom 1.12.0-beta5)
$ mv ~/.atom ~/.atom.save # moves your real environment out of the way
$ apm-beta install faketerm2
Installing faketerm2 to {{~}}/.atom/packages ✓
$ atom-beta
(Ctrl-`)
Terminal appears
```
(Be sure to `rm -rf ~/.atom; mv ~/.atom.save ~/.atom`)

**Comment by Fred-Barclay** [comment]
Thanks - will look into it. Since you can install faketerm2, I suspect that my trouble might be because I have both Atom and Atom Beta installed on my system (so two versions of electron?). The error messages would support this interpretation.

What OS are you using?

**Comment by steakknife** [comment]
macOS. I removed atom stable because they do step on each other (not fully isolated, share `~/.atom`) Plus, you MUST rename `Atom Beta.app` to `Atom-Beta.app` and [patch atom.sh to support finding itself.](https://github.com/atom/atom/pull/13042)

**Comment by Fred-Barclay** [comment]
Yup - that was the trouble. Removed Atom and reinstalled Atom Beta and faketerm2 works. 

I do my dev and testing work with faketerm2 so I'll probably break it in a few days. I could merge the current faketerm2 code into a new package (maybe termination-beta or something) if you want so you could use that until Atom 1.12 is stable and I apply the changes to termination. Is that something that could help you?

**Comment by Fred-Barclay** [comment]
Update: working code pushed to the [termination-beta branch](https://github.com/Fred-Barclay/Termination/tree/termination-beta). I'll merge it into master once Atom 1.12 becomes stable.

**Comment by Fred-Barclay** [comment]
I believe that we're now fully compatible with Atom 1.11 *and* Atom 1.12-beta. https://github.com/Fred-Barclay/Termination/commit/0b057744c441ad46b65dc9ef9edb065bd67f2275 @steakknife can you verify?

**Comment by steakknife** [comment]
Works!

**Comment by Fred-Barclay** [comment]
Yahoo - thanks for opening the original bug and for testing! :smile:
