### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an al...

### ISSUE THREAD

**Issue by thamamur** [Fred-Barclay/Termination#50]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [termination](https://github.com/Fred-Barclay/Termination) package 0.5.1

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At /Users/takumihamamura/.atom/packages/termination/node_modules/jquery/dist/jquery.js:328

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function.globalEval (/packages/termination/node_modules/jquery/dist/jquery.js:328:5)
    at jQuery.domManip (/packages/termination/node_modules/jquery/dist/jquery.js:5435:16)
    at jQuery.append (/packages/termination/node_modules/jquery/dist/jquery.js:5218:15)
    at GitLogView.fill_content (/packages/git-log/lib/git-log-view.js:152:25)
    at GitLogView.log_callback (/packages/git-log/lib/git-log-view.js:73:10)
    at /packages/git-log/lib/git-log-view.js:50:18
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:28.6.0 core:close (input.hidden-input)
     -0:19.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:16.2.0 core:confirm (input.hidden-input)
     -0:16.2.0 git-log:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:15.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-bracket-highlight 0.3.2 
git-log 0.4.1 
indent-guide-improved 1.4.12 
language-slim 0.5.0 
language-stylus 0.2.0 
project-manager 3.3.4 
show-ideographic-space 1.0.2 
smart-tab-name 1.0.5 
termination 0.5.1 
```

**Comment by Fred-Barclay** [comment]
Hi @thamamur 
Thanks for trying Termination!

Can I get from you the steps to reproduce this?
