### ISSUE TITLE
Failed to activate the termination package

### ISSUE THREAD

**Issue by hallaathrad** [Fred-Barclay/Termination#67]
Hey @Fred-Barclay. thanks for taking good care of us.
Once again the Atom update has broken the package, and this time it doesn't let you rebuild it, no matter how many times I've uninstalled and reinstalled it.

To be fair, I'm on 1.23.0-beta0, so I reckon the bug won't reach the mainstream in the next few days/weeks. But just a heads up before it does.
Here's the call stack:

TypeError: target[Symbol.iterator] is not a function
    at TooltipManager.add (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\tooltip-manager.js:117:35)
    at StatusBar.module.exports.StatusBar.initialize (~/.atom/packages/termination/lib/status-bar.coffee:104:38)
    at StatusBar.View [as constructor] (~\.atom\packages\termination\node_modules\space-pen\lib\space-pen.js:184:25)
    at new StatusBar (~/.atom/packages/termination/lib/status-bar.coffee:11:7)
    at Object.consumeStatusBar (~/.atom/packages/termination/lib/termination.coffee:17:26)
    at Provider.module.exports.Provider.provide (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\node_modules\service-hub\lib\provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.consume (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\node_modules\service-hub\lib\service-hub.js:50:24)
    at Package.module.exports.Package.activateServices (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\package.js:456:81)
    at Package.module.exports.Package.activateNow (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\package.js:258:22)
    at ~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\package.js:227:38
    at Package.module.exports.Package.measure (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\package.js:99:21)
    at ~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\package.js:220:32
    at Package.module.exports.Package.activate (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\package.js:217:40)
    at PackageManager.activatePackage (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\package-manager.js:695:42)
    at ~\AppData\Local\atom\app-1.23.0-beta0\resources\app\node_modules\settings-view\lib\package-manager.js:535:35
    at exit (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~\AppData\Local\atom\app-1.23.0-beta0\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

Hope this helps. Cheers and let me know if I can help in any way.

**Comment by Fred-Barclay** [comment]
G'day @hallaathrad and thanks for the report!
I was a bit afraid we'd have this here after reading https://github.com/platformio/platformio-atom-ide-terminal/issues/403. The good news? It looks like it's already been fixed in Atom. :-) I don't know if the new beta with the fix has been pushed out yet or not.

**Comment by hallaathrad** [comment]
Let's hope so! I'll check for updates in the next few days to see if the status changes and then update/close this issue. It seems like there's light at the end of the tunnel, judging from that other issue @ platformio.

Thanks for your quick response!

**Comment by Fred-Barclay** [comment]
Awesome, thanks for keeping me in the loop!

**Comment by Fred-Barclay** [comment]
With Atom 1.23.1 Stable on Windows 7 and Arch I'm not seeing this - I think it's safe to close. Thanks again! 👍
