### ISSUE TITLE
APM install fails

### ISSUE THREAD

**Issue by jameswilliamknight** [Fred-Barclay/Termination#72]
Install command: `apm install termination`

stack trace:

```sh
> pty.js@0.3.0 install /tmp/apm-install-dir-11831-28534-mmds16.6vhnd34n29/node_modules/termination/node_modules/pty.js
> node scripts/install.js


/tmp/apm-install-dir-11831-28534-mmds16.6vhnd34n29
└── (empty)




module.js:471
    throw err;
    ^


Error: Cannot find module '/tmp/apm-install-dir-11831-28534-mmds16.6vhnd34n29/node_modules/termination/node_modules/pty.js/scripts/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11831-28534-mmds16.6vhnd34n29/package.json'
npm WARN apm-install-dir-11831-28534-mmds16.6vhnd34n29 No description
npm WARN apm-install-dir-11831-28534-mmds16.6vhnd34n29 No repository field.
npm WARN apm-install-dir-11831-28534-mmds16.6vhnd34n29 No README data
npm WARN apm-install-dir-11831-28534-mmds16.6vhnd34n29 No license field.
npm ERR! Linux 4.15.0-13-generic
npm ERR! argv "/snap/atom/141/usr/share/atom/resources/app/apm/bin/node" "/snap/atom/141/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/james/.atom/.apm/.apmrc" "--userconfig" "/home/james/.atom/.apmrc" "install" "/tmp/d-11831-28534-1yoyngp.kkqh5jnhfr/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE


npm ERR! pty.js@0.3.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11831-28534-mmds16.6vhnd34n29/npm-debug.log
npm ERR! code 1
```

**Comment by octoquad** [comment]
Works ok without Atom being packaged as a Snap:

```
$ apm install termination
Installing termination to /home/user/.atom/packages ✓
$ atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by jameswilliamknight** [comment]
No more snapping for me then. Thanks @octoquad
