### ISSUE TITLE
Terminal does not load on Arch 

### ISSUE THREAD

**Issue by Fred-Barclay** [Fred-Barclay/Termination#86]
Problem: Can't type in terminal. It loads but only a blinking cursor is shown.

Occurs: Only observed on Arch Linux.

Atom info: 
```
$ apm --version
apm  2.1.3
npm  6.5.0
node 11.5.0 x64
atom 1.33.1
python 2.7.15
git 2.20.1
```

Steps to reproduce:
1. Start Atom
2. Open termination

__This appears to be an incompatibility with the pty.js backend. I'll keep this updated as I learn more.__

Relevant debug warnings:

```
task.coffee:77 
{errno: -2, syscall: "lstat", code: "ENOENT", path: "/home/fred/.atom/packages/termination/node_modules/pty.js/bin/linux/x64_m64/pty.node.bak"}
code
:
"ENOENT"
errno
:
-2
path
:
"/home/fred/.atom/packages/termination/node_modules/pty.js/bin/linux/x64_m64/pty.node.bak"
syscall
:
"lstat"
__proto__
:
Object
(anonymous)	@	task.coffee:77
(anonymous)	@	task.coffee:137
simpleDispatch	@	/usr/lib/atom/node_m…/dist/emitter.js:64
emit	@	/usr/lib/atom/node_m…dist/emitter.js:257
(anonymous)	@	task.coffee:89
emit	@	events.js:182
emit	@	internal/child_process.js:811
_tickCallback	@	internal/process/next_tick.js:63
```
```
annot find module '/home/fred/.atom/packages/termination/node_modules/pty.js/bin/linux/x64_m64/pty.node' Error: Cannot find module '/home/fred/.atom/packages/termination/node_modules/pty.js/bin/linux/x64_m64/pty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/fred/.atom/packages/termination/node_modules/pty.js/lib/pty.js:27:9)
    at Object.<anonymous> (/home/fred/.atom/packages/termination/node_modules/pty.js/lib/pty.js:487:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/fred/.atom/packages/termination/node_modules/pty.js/index.js:2:18)
    at Object.<anonymous> (/home/fred/.atom/packages/termination/node_modules/pty.js/index.js:4:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/fred/.atom/packages/termination/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/fred/.atom/packages/termination/lib/process.coffee:1:1)
    at Object.<anonymous> (/home/fred/.atom/packages/termination/lib/process.coffee:1:1)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
(anonymous) @ task.coffee:77
(anonymous) @ task.coffee:137
simpleDispatch @ /usr/lib/atom/node_modules/event-kit/dist/emitter.js:64
emit @ /usr/lib/atom/node_modules/event-kit/dist/emitter.js:257
(anonymous) @ task.coffee:89
emit @ events.js:182
emit @ internal/child_process.js:811
_tickCallback @ internal/process/next_tick.js:63
```

**Comment by lectrode** [comment]
For anyone looking for a "quick" workaround, the [flatpak package](https://flathub.org/apps/details/io.atom.Atom) for Atom works.

**Comment by wpfan2099** [comment]
hello dear all - i am  workin on manjaro - and i also am not able to run termination. 
plz advice...
ps . keep up the great project - it rocks

**Comment by the-j0k3r** [comment]
@Fred-Barclay feel free to pull the patch node-pty-prebuilt and change authors, see `git commit --amend --author="Author Name <email@address.com>"`

**Comment by Fred-Barclay** [comment]
Excellent, thanks @the-j0k3r :smile: 

This issue should be closed now. Please update and let me know if there are still any problems. 
Cheers!

**Comment by wpfan2099** [comment]
Many many Thanks.  Ive been waitin for this fix . IT IS wanted and needed
Herr so badly greetings Martin

Am Di., 1. Jan. 2019, 09:46 hat the-j0k3r <notifications@github.com>
geschrieben:
