### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\termination\lib\process.coffee'

### ISSUE THREAD

**Issue by ekopras18** [Fred-Barclay/Termination#88]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [termination](https://github.com/Fred-Barclay/Termination) package 0.7.1

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\Pras\.atom\packages\termination\lib\process.coffee'

```
At module.js:545

Error: Cannot find module 'C:\Users\Pras\.atom\packages\termination\lib\process.coffee'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:154667)
    at Function.resolve (internal/module.js:18:19)
    at Function.customRequire.resolve (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:4703780)
    at new Task (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:35529)
    at Function.t.exports.Task.once (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:36436)
    at TerminationView.module.exports.TerminationView.forkPtyProcess (/packages/termination/lib/view.coffee:237:19)
    at TerminationView.module.exports.TerminationView.displayTerminal (/packages/termination/lib/view.coffee:252:30)
    at /packages/termination/lib/view.coffee:404:19
    at /packages/termination/lib/view.coffee:782:11)
    at HTMLDivElement.fn (/packages/termination/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/termination/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/termination/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Non-Core Packages

```
termination 0.7.1 
```

**Comment by Fred-Barclay** [comment]
Hi @ekopras18 that's really strange. Can you verify that C:\Users\Pras.atom\packages\termination\lib\process.coffee does in fact exist? If so maybe something went wrong during installation -- I would try removing Termination and then reinstalling it.

Cheers!
Fred

**Comment by Fred-Barclay** [comment]
Closing for now. @ekopras18 feel free to reopen if this is still an issue!

**Comment by Jakkalsie** [comment]
Hey Fred
I have been getting the same error with the package, but my whole lib folder is not even there to begin with. Does it matter if I use Windows?

**Comment by Fred-Barclay** [comment]
@Jakkalsie It shouldn't matter -- I use Windows 7 at work and termination works fine there. Strange.

Maybe try the old "uninstall and reinstall"?

**Comment by Jakkalsie** [comment]
It worked thanks!
