### ISSUE TITLE
404 Not Found: node-pty-multiarch

### ISSUE THREAD

**Issue by Aerijo** [Fred-Barclay/Termination#98]
Looks like the module name should be [node-pty-prebuilt-multiarch](https://www.npmjs.com/package/node-pty-prebuilt-multiarch)

**Comment by Fred-Barclay** [comment]
On it, thanks!

**Comment by Fred-Barclay** [comment]
@Aerijo Thank you so much, it should be fixed now! :smile: :tada:

**Comment by Aerijo** [comment]
Yup, it works

**Comment by aviatesk** [comment]
Can this solve the build problem within Electron v3 (And hopefully v4 as well) ?

**Comment by Aerijo** [comment]
@aviatesk The current release should handle all current Atom versions (Nightly is on Electron 4).

**Comment by aviatesk** [comment]
@Aerijo 
On Windows 10, I got the error below in console and terminal just doesn't work...
```
<embedded>:14 Cannot find module '..\build\Debug\conpty.node' Error: Cannot find module '..\build\Debug\conpty.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.loadNative (C:\Users\aviat\.atom\packages\termination\node_modules\node-pty-prebuilt-multiarch\lib\utils.js:22:16)
    at new WindowsPtyAgent (C:\Users\aviat\.atom\packages\termination\node_modules\node-pty-prebuilt-multiarch\lib\windowsPtyAgent.js:34:40)
    at new WindowsTerminal (C:\Users\aviat\.atom\packages\termination\node_modules\node-pty-prebuilt-multiarch\lib\windowsTerminal.js:49:24)
    at Object.fork (C:\Users\aviat\.atom\packages\termination\node_modules\node-pty-prebuilt-multiarch\lib\index.js:34:12)
    at Object.module.exports (file:///C:/Users/aviat/.atom/packages/termination/lib/process.coffee:25:22)
    at process.<anonymous> (C:\Users\aviat\AppData\Local\atom\app-1.39.1\resources\app.asar\src\task-bootstrap.js:69:43)
    at process.emit (events.js:182:13)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(anonymous) @ <embedded>:14
(anonymous) @ <embedded>:14
simpleDispatch @ <embedded>:11
emit @ <embedded>:11
(anonymous) @ <embedded>:14
emit @ events.js:182
emit @ internal/child_process.js:811
_tickCallback @ internal/process/next_tick.js:63
```

**Comment by aviatesk** [comment]
Umm reinstall stuff doesn't seem to help.

**Comment by aviatesk** [comment]
Opened up the new issue #99 :)
